version: '3.8'

services:
  # PostgreSQL database with pgvector extension
  db:
    image: pgvector/pgvector:pg16
    container_name: financial-advisor-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_advisor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Backend FastAPI application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial-advisor-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Database
      DATABASE_URL: postgresql://postgres:postgres@db:5432/financial_advisor
      DEBUG_SQL: "false"
      AUTO_CREATE_PGVECTOR_EXTENSION: "true"
      
      # OAuth - Set these in production
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-your-google-client-id}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-http://localhost:8000/auth/google/callback}
      
      HUBSPOT_CLIENT_ID: ${HUBSPOT_CLIENT_ID:-your-hubspot-client-id}
      HUBSPOT_CLIENT_SECRET: ${HUBSPOT_CLIENT_SECRET:-your-hubspot-client-secret}
      HUBSPOT_REDIRECT_URI: ${HUBSPOT_REDIRECT_URI:-http://localhost:8000/auth/hubspot/callback}
      
      # Security
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production}
      
      # Frontend
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      
      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your-openai-api-key}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app:/app/app
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
