"""add calendar watcher fields to user"""

# revision identifiers, used by Alembic.
revision = '0f2eae8ae0a5'
down_revision = 'add_parent_task_id'
branch_labels = None
depends_on = None

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('snippet',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('body_plain',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('body_html',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('external_source',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('memoryrule', schema=None) as batch_op:
        batch_op.alter_column('rule_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('last_error',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_channel_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('calendar_resource_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('calendar_watch_expiration', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_calendar_channel_id'), ['calendar_channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_calendar_resource_id'), ['calendar_resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_calendar_watch_expiration'), ['calendar_watch_expiration'], unique=False)

    with op.batch_alter_table('vectoritem', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vectoritem', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_calendar_watch_expiration'))
        batch_op.drop_index(batch_op.f('ix_user_calendar_resource_id'))
        batch_op.drop_index(batch_op.f('ix_user_calendar_channel_id'))
        batch_op.drop_column('calendar_watch_expiration')
        batch_op.drop_column('calendar_resource_id')
        batch_op.drop_column('calendar_channel_id')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('last_error',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('memoryrule', schema=None) as batch_op:
        batch_op.alter_column('rule_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.alter_column('external_source',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('body_html',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('body_plain',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('snippet',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
